### ISSUE TITLE
[Improvement]: Container Info and Network tab (for each container and service)

### ISSUE THREAD

**Issue by peaklabs-dev** [coollabsio/coolify#2495]
### Description

I had a deep look into the coolify containers and found some things I believe could be improved (hope I can help like this as I am at the moment not ready to start code contributing)

### Minimal Reproduction (if possible, example repository)

Network page on the individual Container/ services:
- [ ] Let us select network via dropdown and also see which network the container is in
- [ ] Make sure we can connect containers to networks from the UI after they are created, especially for databases this would be great as they do not have a predefined network checkbox. The ability to have a UI where we can select networks would also eliminate the connect to predefined network checkbox, as if we select a network when creating or on the Network tab, it will automatically connect to that.
- [ ] When you select a network when creating a resource, it is automatically connected to the resource without you having to check a checkbox.
- [ ] Let us remove networks with a click of a button
- [ ] let us add multiple networks to the container 3-4...
- [ ] Also enabled Ipv6 on docker networks (all of them should have Ipv4 and Ipv6): https://github.com/coollabsio/coolify/discussions/4048

General info tab for the current container:
- [ ] IPv4 and IPv6 IP addresses displayed for the container with a copy button
- [ ] Mac Adresse is displayed here in the network tab for the container
- [ ] let us see the container ID 
- [ ] Let us see the container name -> the name with the uuid
- [ ] Let us set the container name for databases manually if we want
- [ ] container Image hash 
- [ ] when was the container create
- [ ] when was it startet -> especially for services
- [ ] when was the image last pulled
- [ ] when was the container updated -> depended on this: https://github.com/coollabsio/coolify/issues/2500

**Comment by Cybertronus** [comment]
Bump, this would be extremely useful for many

**Comment by seeker71** [comment]
/attempt #2495

Implementation plan:
1. Implement a focused Container Info + Network tab enhancement for container/service pages.
2. Add network selection/visibility (including current network membership) and core container metadata requested in the issue.
3. Keep the change scoped and reviewable, with backward-compatible defaults and no regressions for existing views.
4. Submit PR with `/claim #2495` and include a short demo video per bounty rules.

**Comment by babata990725** [comment]
/attempt #2495

Scoped implementation plan (1-3h):
- Add a read-only "Container Info" section (container ID, container name, image, created/started timestamps, IPv4/IPv6 when available).
- Add copy buttons for ID and IP values.
- Keep network changes out-of-scope for this pass to keep PR small/reviewable.

If this scoped slice is acceptable despite existing WIP attempts, I can open a PR with /claim #2495 and demo video.

**Comment by gent33112-wq** [comment]
I can work on this!

**Timeline:** Ready

**Payment:** gent33112-wq

**Comment by justinleeyang** [comment]
Quick follow-up on #2495: I am still actively working on this. Please let me know if you want me to narrow scope to a smaller first PR.

**Comment by justinleeyang** [comment]
Quick follow-up on #2495: I am still actively working on this. Please let me know if you want me to narrow scope to a smaller first PR.

**Comment by justinleeyang** [comment]
Quick follow-up on #2495: I am still actively working on this. Please let me know if you want me to narrow scope to a smaller first PR.

**Comment by justinleeyang** [comment]
No maintainer response yet on #2495, I will switch to another open bounty for now and can resume this issue anytime when feedback arrives.

**Comment by Cinzya** [comment]
@justinleeyang please refrain from spamming our issues with hourly update requests. If you are in need of a quick response from the maintainers, then join our Discord and ask there. 
This is not the place for it.
If you continue to do so, we will see ourselves forced to ban you.

**Comment by JasonDavis666** [comment]
/attempt #2495

Implementation plan:
1. Keep this to a narrow, reviewable first slice: add a read-only Container Info section for each container/service page with container ID, container name, image, created/started timestamps, and IPv4/IPv6 values when available.
2. Add copy actions for stable identifiers/IP fields only; do not bundle network-editing or multi-network management into this first pass.
3. Reuse existing page structure/components, add focused regression coverage for the rendered info/copy affordances, and target `next` with `/claim #2495` plus the required short demo video if the implementation lands cleanly.

Goal: submit a small, payable first PR instead of the full issue wishlist in one shot.

**Comment by harishn1408** [comment]
### Proposed Solution

### Analysis
The issue is about enhancing the container info and network tab in the coolify UI. The root cause is the lack of features and information in the current implementation. This can be addressed by modifying the UI components and API calls.

### Implementation Plan
1. Update `src/components/Container/NetworkTab.js` to include a network dropdown and add/remove network buttons.
2. Modify `src/api/containers.js` to handle network connections and disconnections.
3. Add IPv6 support to docker networks in `src/utils/docker.js`.

### Code Changes
```javascript
// src/components/Container/NetworkTab.js
import React from 'react';
import { useState, useEffect } from 'react';
import { getContainerNetworks, updateContainerNetworks } from 'src/api/containers';

const NetworkTab = () => {
  const [networks, setNetworks] = useState([]);
  const [selectedNetwork, setSelectedNetwork] = useState(null);

  useEffect(() => {
    getContainerNetworks().then((data) => setNetworks(data));
  }, []);

  const handleNetworkChange = (network) => {
    setSelectedNetwork(network);
    updateContainerNetworks(network);
  };

  return (
    <div>
      <select value={selectedNetwork} onChange={(e) => handleNetworkChange(e.target.value)}>
        {networks.map((network) => (
          <option key={network.id} value={network.id}>
            {network.name}
          </option>
        ))}
      </select>
      <button onClick={() => updateContainerNetworks(null)}>Remove Network</button>
    </div>
  );
};

export default NetworkTab;
```

### Testing Suggestions
- Test the network dropdown and add/remove network buttons.
- Verify that containers can be connected to multiple networks.
- Check that IPv6 is enabled on docker networks.

---
<sub>Happy to submit a PR implementing this approach if it looks good to the maintainers.</sub>

**Comment by Ivy138** [comment]
/attempt #2495

I am taking a narrow, reviewable first slice: add a read-only Container Info tab under application, database, and service configuration. Scope is container ID/name, image/image ID, status, created/started timestamps, restart count, and Docker network IPv4/IPv6/MAC data from `docker inspect`. This intentionally avoids network mutation in the first PR so the change stays small and safe.

**Comment by JIMT111** [comment]
/attempt #2495

I’d like to work on a small, focused slice of this bounty.

Plan:
1. Add a read-only Container Info section/tab for individual service/container views.
2. Show core container metadata that is already available from the existing backend response, such as container ID/name, image, status, created/started timestamps, and IP/network details if present.
3. Avoid changing network attach/detach behavior in this PR to keep the scope small and reviewable.
4. Include a short demo video in the PR and add `/claim #2495` in the PR body if the implementation is accepted.

Please let me know if this scoped slice is acceptable before I start.

**Comment by CatfishW** [comment]
/attempt #2495

Focused first slice plan:
1. Add a read-only Container Info view for individual service application and service database pages.
2. Populate it from live `docker inspect` data on the resource server: container ID, runtime container name, image reference / image hash when available, status, created time, started time, restart count, and per-network IPv4 / IPv6 / MAC details.
3. Keep network mutation out of scope for this PR so the change stays reviewable and low-risk, but structure the view so connect / disconnect actions can be added later.
4. Include a short demo video and validation notes in the PR body.

I will keep the implementation scoped to the existing service stack item routes rather than introducing a broader redesign.

**Comment by badnikhil** [comment]
/attempt #2495 — see PR #11677 for the implementation plan and screenshot.

PR: #11677

Demo:

![demo](https://raw.githubusercontent.com/badnikhil/coolify/pr-assets/demo-container-info.gif)

**Comment by milos-plavsic** [comment]
Hello maintainers. Before proceeding, could you confirm whether a focused first PR is useful for #2495: a read-only Container Details section in the existing resource modals, populated from live Docker inspect data (container ID/name, image and image ID, status, created/started times, restart count, and per-network IPv4/IPv6/MAC/aliases)? It would intentionally exclude network attach/detach, persistent network selection, IPv6 network creation, database renaming, and image history. I have a locally tested draft, but will not open a PR unless this scope is acceptable.

**Comment by Furox-Art** [comment]
/attempt #2495

Plan: Add a Network tab experience on the container/service detail page that (1) shows the container's current network(s), and (2) allows selecting/connecting a network via a dropdown from the UI, covering databases without a predefined-network checkbox.

**Comment by Cinzya** [comment]
FYI, we stopped the bounty program with Algora. We asked them to remove issues which are still open like this one. Even if you still see a open issue on their site, payouts won't work / happen and we don't accept any bounty claims. PRs can still be made regardless but don't expect a payout from Algora.
