### ISSUE TITLE
[Bug]: Inconsistent service settings and missing tabs/settings for certain services.

### ISSUE THREAD

**Issue by ayntk-ai** [coollabsio/coolify#2524]
### Description

This issue is persistent over a number of services. I would suggest a quick review of all of them to make sure that all are somewhat equal. I have checked a few and noted the missing things for them.

### Minimal Reproduction (if possible, example repository)

- When a service stack has a Database the service stack tab is different:
Service Stack Tab:
![image](https://github.com/coollabsio/coolify/assets/122374094/0d108f4e-93ba-4daa-af3e-e75f49f1a452)
-> These are the Maria DB settings (yes I can set them in evrionment varaiables but also here.)
Classic Press for example also with maria DB does not have these settings:
![image](https://github.com/coollabsio/coolify/assets/122374094/ce670edc-9f4c-4a11-9247-6b33c90dbc59)
On another service, it looks different again:
![image](https://github.com/coollabsio/coolify/assets/122374094/55ac32ea-a264-464f-8c22-58ec74faa6ee)
--> You could also look at ghost there it looks different again.
- [ ] Streamline Database settings/ Service Specific Configuration for services, so all have the same UI and the same way of doing things. Setting Database password and so on --> see classic press and WordPress service specific configuration to see the differences

- There are a lot of important settings missing for services that I believe should be there and are also needed (a non-exhaustive list below):
- [ ] There is no **Force Https** setting for some containers -> most services these setting is missing --> example WordPress Container --> see issue: https://github.com/coollabsio/coolify/issues/2513
- [ ] No preview deployments for docker images and commits -> settings and tab is missing (not implemented yet) --> see issue: https://github.com/coollabsio/coolify/issues/2510
- [ ] Use a build server is not available on most services only on git services
- [ ] No custom docker options available on most services 
- [ ] Network settings completely missing form services containers -> Porst expose and Ports mapping
- [ ] **There is no way at the moment to update/ add container labels --> For example set basic auth in front of PHP with services --> as the docker compose file when viewed with container labels is not editable and the container labels are not in the UI to edited them** --> add container labels back to the UI for services and also allow us to add docker tags --> see: https://github.com/coollabsio/coolify/issues/2497
- [ ] Sort alphabetically feature for Environment variables is not available on services
- [ ] Also show hardcoded variables in the Environment Variables UI (read-only) -> so we can see all environment variables
- [ ] No server tab in services where we can see server related configurations
- [ ] Health checks tab is completely missing for the UI -> add it back for services (maybe read only)
- [ ] Rollback tab for services with docker images (or cutom build docker images) -> especially for services the rollback tab would be needed. See also update issue: https://github.com/coollabsio/coolify/issues/2500
- [ ] **No Resource Limits tab for service containers, this tab is missing pleas add it**
- [ ] Custom docker registry in image field support: see also image management: https://github.com/coollabsio/coolify/issues/2499
- [ ] No Deployments tab (needs to be added after docker image and commit based preview deployments are available) https://github.com/coollabsio/coolify/issues/2510
- [ ] No connect to predefined network checkbox for git sources is available
- [ ] **Direction setting -> www redirection is only available on git deployments. Make the www redirection setting also available on containers like WordPress containers**

Missing Database settings in a service Database:
- [ ] Initial Database Arguments missing
- [ ] Host Auth Method is also missing
- [ ] no port mapping for the database in a service
- [ ] **no internal URL for databases in services**
- [ ] Initialization scripts for databases in services
- [ ] **no custom Configuration for databases in services**
- [ ] No server tab for the database container in services
- [ ] Import backup page missing for databases in services -> see issue: https://github.com/coollabsio/coolify/issues/2501
- [ ] Ressource limits for Databse/ all Containers in a stack/ services is missing
- [ ] When just deploying a database there are no environment variables in the UI but they are set in the UI display them like for maria DB databse in a service also in the UI:
UI setting: 
![image](https://github.com/coollabsio/coolify/assets/122374094/577ef4ba-e89d-4996-bc52-a13e290772b7)
in the UI of this there are no variables set, if I look at a MaraDB in a service there are variables there:
![image](https://github.com/coollabsio/coolify/assets/122374094/bacdf9ff-2648-4ee8-9c4e-49a4c9e06231)

Then the Deploy settings are not streamlined across containers and services (make sure to add theses to them):
- [ ] Force Deploy without cache is missing form services
- [ ] redeploy and pull latest image is named differently on normal services (git services) it just is redeploy there
- [ ] Stop button and Start/ deploy button on all of them
- [ ] A force kill button would be great if a container is stuck: https://github.com/coollabsio/coolify/issues/2497
- [ ] Sometime there is just a button restart degraded services -> where is the redeploy button then on services for examples?
- [ ] No re-deploy button for databases just start and stop -> what if the image changes or the current image has an minor update, re-deploy needs to be possible?
- [ ]

- 

### Version

v4.0.0-beta.297
