### ISSUE TITLE
[Bug]: UI Responsiveness

### ISSUE THREAD

**Issue by iamdineshkumar** [coollabsio/coolify#458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In UI there are some responsive issue. When I tried to access in mobile browser i faced following 

1. In Login UI input fields are not properly aligned(Minor)
2. When open existing Application UI is not totally responsive and not able to view any details in screen
3. When open existing database/service UI is better text lables got under left side menu bar as well as in top bar right side UI components are overlapped with left side UI components

### Steps To Reproduce

Kindly check in mobile browser or use inspect element in desktop browser

### Version

2.9.7

**Comment by hdbham** [comment]
Hi! I found a few more.

Rather than find every relative path, i'll name the pages using h1 and means of navigation. 
I likely wont catch everything on first go,

## Subtasks

#### Dashboard
- [ ] update breakpoint prefixes for elements under _"Resources"_  so no longer collides with with nav. 
- >  changing height and width of icons helps, but padding may need to change 

- [ ] update breakpoint prefixes for elements under _"Hardware Details"_ , `stat-value` 
- > padding may be unnecessary on mobile, _"Load Average"_ uncenters under 400px if all values above 2 digits

#### App > Configuration
- [ ] h1 collides with nav-side
- [ ] fix padding/centering for inputs  
- > change padding

####  Gitlab > Configuration
- [ ] `<div class="p-2 text-xs text-stone-400 w-full">` collides with nav

#### Docker > destinations
- [ ] fix padding/centering for inputs

#### General database configuration 
- [ ] copy svg not aligned right

:smile: 
:)

**Comment by LLxD** [comment]
Nice job finding all that @hdbham and @iamdineshkumar! In the current state of coolify, I think the best next steps are improving componentization (so changes made in one place reflect on all others) and fixing both lists task by task.

Keep it up with the reports and nice job posting on the corresponding issue @hdbham so we can have the tracking of it later 🚀.

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
